// This file is auto-generated by scripts/gen-build-info.mjs
export const buildInfo = {
  envLabel: "local",
  appVersion: "0.1.0",
  gitShaShort: "b6aaa64",
  buildTimeIso: "2026-04-08T15:39:50.782Z",
} as const;
