// This file is auto-generated by scripts/gen-build-info.mjs
export const buildInfo = {
  envLabel: "local",
  appVersion: "0.1.0",
  gitShaShort: "fe86b8d",
  buildTimeIso: "2026-03-23T14:27:12.448Z",
} as const;
