// This file is auto-generated by scripts/gen-build-info.mjs
export const buildInfo = {
  envLabel: "local",
  appVersion: "0.1.0",
  gitShaShort: "d91dbf6",
  buildTimeIso: "2026-04-08T18:40:24.791Z",
} as const;
